import { Box, Typography } from "@mantine/core";
import Head from "next/head";
import styles from "../../styles/Login.module.css";
import Image from "next/image";
import { TextInput, PasswordInput, Button, Card, Anchor } from '@mantine/core';
export default function Home() {
    return (
        <>
            <Head>
                <title>Trasncript converter chat Signup</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Box h={"100vh"} display={"flex"} className={styles.loginMain}>

                    <Card shadow="sm" padding="lg" radius="md" withBorder w={"500px"}>
                        <Typography variant={"h4"} component={"h4"} ta="center">Welcome Back</Typography>
                        <Typography variant={"h2"} component={"h2"} ta="center">Signup to continue</Typography>
                         <TextInput
                            placeholder="Enter your username"
                            m="xs"
                            size="md"
                        />
                        <TextInput
                            placeholder="Enter your email"
                            m="xs"
                            size="md"
                        />
                        <PasswordInput
                            placeholder="Create your password"
                            m="xs"
                            size="md"
                        />
                       
                        {/* <Anchor href="https://mantine.dev/" target="_blank" ta="right" c="#3F3EED !important" mt="xs">
                            Forgot password?
                        </Anchor> */}
                        <Button fullWidth mt="xl" size="md">Create Account</Button>
                        <Typography variant={"body1"} component={"p"} ta="center" mt="md">If you have an account?

                            <Anchor href="/" ta="right" c="#3F3EED !important" mt="xs" ml={"xs"}>
                                Sign In
                            </Anchor>
                        </Typography>
                    </Card>
                </Box>

            </div>
        </>
    );
}
